# Generated by Django 3.0 on 2019-12-18 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20191214_1916'),
    ]

    operations = [
        migrations.RunSQL(
            "insert into roles values (1,now(),now(),'Student', 'student'),"
            "(2,now(),now(),'Teacher', 'teacher'),"
            "(3,now(),now(),'Assistant', 'assistant')")
    ]
