# Generated by Django 3.0 on 2019-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0002_auto_20191219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
