# Generated by Django 3.0 on 2019-12-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tests', '0004_auto_20191222_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
