# Generated by Django 3.0 on 2019-12-27 15:13

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('analytics', '0003_auto_20191227_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedtest',
            name='student',
            field=models.ForeignKey(default=users.models.Student.get_anonymous_student, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='solved_tests', to='users.Student'),
        ),
    ]
