# Generated by Django 3.0 on 2019-12-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20191227_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solvedtest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='solvedtest',
            constraint=models.UniqueConstraint(condition=models.Q(is_checked=False), fields=('test', 'student'), name='only_one_test'),
        ),
    ]
